# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, primitive, tasty, tastyQuickcheck, transformers, vector }:

cabal.mkDerivation (self: {
  pname = "loops";
  version = "0.2.0.2";
  src = ./.;
  buildDepends = [ primitive transformers vector ];
  testDepends = [ tasty tastyQuickcheck ];
  meta = {
    description = "Fast imperative-style loops";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
